name: Blank Issue
description: Create a blank issue for anything not covered by other templates
title: 'Blank: '
labels: ['blank']
body:
  - type: markdown
    attributes:
      value: |
        Please describe your issue below. You can use this template for any feedback, bug, feature request, or other topics not covered by the specific templates.
  - type: textarea
    attributes:
      label: Description
      description: Please provide a clear and concise description of your issue or request.
      placeholder: Describe your issue here.
    validations:
      required: true
